# Generated by Django 5.0.6 on 2024-06-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cart_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('cart_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('item_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cart_id', models.IntegerField()),
                ('order_created', models.DateField(auto_now_add=True)),
                ('payment', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='product')),
                ('product_category', models.CharField(max_length=200, verbose_name='categories')),
                ('product_price', models.IntegerField(default=0, verbose_name='price')),
                ('product_quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('Product_description', models.CharField(max_length=300, verbose_name='description')),
                ('product_features', models.CharField(max_length=300, verbose_name='features')),
                ('product_created', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('product_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
            ],
        ),
        migrations.CreateModel(
            name='shippingAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('estate', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='shippingPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=100)),
                ('estate', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
