# Generated by Django 4.2.13 on 2024-07-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='location',
            new_name='estate',
        ),
    ]
