# Generated by Django 4.2.13 on 2024-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_1',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
