# Generated by Django 4.2.13 on 2024-07-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_location_addresses_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='shop.products'),
        ),
    ]
