# Generated by Django 4.2.13 on 2024-07-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_images_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='estate',
            new_name='major_road',
        ),
    ]
