# Generated by Django 4.2.13 on 2024-09-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cartitems_product_alter_images_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.orders'),
        ),
    ]
